name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  python-tests:
    name: Python Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"] # Focus on latest stable versions

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run Python test suite
        run: |
          cd public/python
          echo "🧪 Running Python Chronicles Test Suite"
          python tests/run_all_tests.py

  nextjs-build:
    name: Next.js Build & Test
    runs-on: ubuntu-latest
    needs: python-tests # Only run if Python tests pass

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint --if-present || echo "No lint script found"

      - name: Build Next.js application
        run: npm run build

      - name: Run tests
        run: npm test --if-present || echo "No test script found"

  deployment-ready:
    name: Deployment Ready
    runs-on: ubuntu-latest
    needs: [python-tests, nextjs-build]
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deployment ready notification
        run: |
          echo "🚀 All tests passed! Application is ready for deployment."
          echo "✅ Python tests: Passed"
          echo "✅ Next.js build: Passed"
          echo "🎉 Ready to deploy to production!"
